/* Copyright 2026 上海如静知华信息科技有限公司 */
export const domain={
 code:'CASHFLOWAI',systemName:'知华现金流预测 AI 平台',englishName:'CASH FLOW FORECAST AI',theme:{primary:'#315b7d',dark:'#243a51',accent:'#c99b4e'},
 workspace:'集团财资中心 / 现金流管理组',fieldWorkspace:'华东区域 / 财务共享中心',period:'2026-08-15 · 30 日滚动',liveText:'资金数据于 10:35 更新',fieldContextLabel:'预测周期',fieldContext:'未来 30 天',fieldUser:'陆清',fieldRole:'资金专员',adminUser:'唐越',adminRole:'集团资金负责人',
 adminTitle:'集团现金流驾驶舱',adminBreadcrumb:'财资智能 / 流动性态势',adminSubtitle:'连接收款、付款、应收与授信数据，预测资金缺口并形成可解释的流动性处置建议。',exportAction:'导出资金报告',createAction:'新建预测任务',
 chartTitle:'可用资金滚动趋势',chartSubtitle:'预测余额 / 安全水位',chartLabels:['01日','05日','09日','13日','17日','21日','25日','29日','31日'],loadTitle:'法人资金风险',loadSubtitle:'高风险主体占当前纳管法人比例',recordsTitle:'重点现金流预测任务',recordsSubtitle:'按缺口规模、覆盖天数和付款窗口排序',issueTitle:'需要处理的流动性风险',issueSubtitle:'来自回款延期、集中付款和授信额度',
 recordName:'预测任务',itemName:'资金主体',unitName:'责任团队',batchName:'预测口径',planName:'核对项',doneName:'已确认',exceptionName:'偏差',unitLabel:'项',
 listBreadcrumb:'现金流 / 预测任务',listSubtitle:'将收支计划、应收账款和授信数据汇总为可解释的流动性优先级。',listSummary:[['纳管主体','42'],['本周预测','36'],['高风险','5',true],['已处置','18']],tabs:['全部','待预测','处置中','待复核','已归档'],
 fieldBreadcrumb:'资金工作台 / 资金专员',fieldTitle:'现金流预测工作台',fieldSubtitle:'负责主体 8 家 · 今日核对 12 项 · 待处理风险 3 条',fieldSecondary:'查看资金日历',reportAction:'提交资金反馈',fieldNoticeTitle:'银企数据同步正常',fieldNotice:'核心账户覆盖率 98.6%',
 steps:['数据汇聚','收支预测','缺口识别','人工处置','结果复盘'],documentAction:'查看主体档案',printAction:'导出资金处置单',resourceCardTitle:'财资数据资源',resourceValueLabel:'接入账户',resourceHealthLabel:'数据健康度',quickSubtitle:'常用财资入口',
 quickActions:[['流动性预测','/shopfloor/report','收款、付款与授信证据'],['主体档案','/shopfloor/material','法人、账户和授信信息'],['数据资源','/shopfloor/resources','银企直连、ERP 和模型'],['风险升级','/shopfloor/andon','重大缺口与集中付款协同']],
 reportDefaults:[6,1],reportTitle:'现金流预测反馈',reportSubtitle:'记录回款承诺、付款调整和授信安排。',reportSuccess:'资金预测反馈已提交',reportPlaceholder:'填写收支变化、回款承诺、付款优先级和处置动作',reportFootnote:'提交后进入集团资金负责人复核队列',ruleTitle:'资金预测决策门禁',ruleSubtitle:'CASHFLOW-AI · V1.0',rules:[['账户数据','余额必须可核验'],['授信提款','授权人员审批'],['预测调整','保留原因证据'],['结果复盘','周期结束后执行',true]],fieldTotals:[['8','负责主体'],['3','待处理风险'],['12','今日核对'],['98.6%','账户覆盖率']],
 adminMenus:[['/admin','home','现金流驾驶舱'],['/admin/work-orders','order','预测任务'],['/admin/samples','box','资金主体'],['/admin/schedule','calendar','资金日历'],['/admin/methods','process','预测规则'],['/admin/reviews','quality','处置复核'],['/admin/resources','machine','数据资源'],['/admin/report','chart','流动性分析']],fieldMenus:[['/shopfloor','home','资金工作台'],['/shopfloor/report','report','预测反馈'],['/shopfloor/tasks','order','我的任务'],['/shopfloor/material','box','主体档案'],['/shopfloor/resources','machine','账户状态'],['/shopfloor/andon','risk','风险升级',3]],
 moduleTitles:{tasks:['我的预测任务','查看缺口、覆盖天数和处置状态'],material:['资金主体档案','查看法人、账户、授信和付款习惯'],resources:['财资数据中心','管理银企直连、ERP 和预测模型'],andon:['流动性风险升级','提交重大缺口和付款冲突'],samples:['资金主体台账','统一管理法人和账户结构'],schedule:['资金收支日历','协调回款、付款与融资窗口'],methods:['现金流预测规则','维护口径、置信度和情景参数'],reviews:['资金处置复核','记录确认、驳回和补充信息'],report:['流动性经营分析','分析余额、缺口和资金成本']},
 tagline:'提前看见资金缺口，守住企业流动性底线',storyTitle:'把分散的收支计划，<br/>变成可信的现金流预测',storyText:'连接银行、ERP 和应收应付数据，帮助资金团队提前准备并坚持人工授权。',pattern:[1,3,6,9,12,15,18,21,24,27,30],loginStats:[['42','纳管主体'],['98.6%','账户覆盖率'],['5','高风险主体']],loginTitle:'集团现金流驾驶舱',adminDemo:'余额 / 缺口 / 授信',fieldDemo:'预测 / 处置 / 复核'}
export const records=[{no:'CF-260815-018',name:'上海制造主体三十日预测',code:'ENTITY-SH-01',unit:'集团资金组',group:'制造板块',plan:12,done:7,exception:3,due:'08-15',batch:'银行+ERP',status:'处置中',progress:58,priority:'高风险'},{no:'CF-260815-021',name:'华东销售主体回款情景',code:'ENTITY-HD-03',unit:'区域财资组',group:'销售板块',plan:9,done:5,exception:1,due:'08-16',batch:'应收+承诺',status:'待复核',progress:56,priority:'关注'},{no:'CF-260815-026',name:'供应链集中付款预测',code:'ENTITY-SC-06',unit:'共享资金组',group:'供应链板块',plan:10,done:2,exception:2,due:'08-16',batch:'应付+授信',status:'待预测',progress:20,priority:'高风险'},{no:'CF-260814-015',name:'深圳服务主体资金滚动',code:'ENTITY-SZ-02',unit:'华南财资组',group:'服务板块',plan:8,done:8,exception:0,due:'08-14',batch:'银行+预算',status:'已归档',progress:100,priority:'正常'},{no:'CF-260815-031',name:'研发主体季度税费情景',code:'ENTITY-RD-08',unit:'集团税资组',group:'研发板块',plan:11,done:7,exception:1,due:'08-17',batch:'税费+预算',status:'处置中',progress:64,priority:'关注'}]
export const resources=[{code:'BANK-01',name:'集团银企直连平台',unit:'财资数字化组',status:'运行中',health:99,value:'126',valueUnit:'户',note:'核心账户余额更新时间小于五分钟'},{code:'MODEL-02',name:'现金流滚动预测模型',unit:'资金策略组',status:'复核中',health:94,value:'v3.0',valueUnit:'',note:'5 个主体进入高风险队列'},{code:'ERP-03',name:'应收应付数据连接器',unit:'财务共享组',status:'预警',health:90,value:'42',valueUnit:'主体',note:'2 家主体付款计划等待回补'}]
export const reviews=[{no:'RV-260815-032',title:'上海制造流动性缺口复核',type:'授信提款',detail:'缺口 22 万元 · 唐越',result:'待确认'},{no:'RV-260815-011',title:'华东销售回款情景确认',type:'预测调整',detail:'6 笔回款 · 陆清',result:'通过'},{no:'RV-260814-018',title:'供应链集中付款窗口',type:'证据补充',detail:'缺少两笔采购付款日期',result:'异常'}]
export const adminMetrics=[['可用资金','1.82 亿元','较昨日增加 3.6%','blue'],['高风险主体','5','预计缺口 860 万元','red'],['三十日净流入','2,480 万元','置信度 86%','green'],['待批处置','7','涉及授信 3,200 万元','orange']]
export const fieldMetrics=[['我的任务','6','3 项高风险','blue'],['今日已核对','12','全部保留来源证据','green'],['待处理风险','3','1 项存在资金缺口','orange'],['账户覆盖率','98.6%','较上周提升 0.4%','slate']]
export const chartActual=[182,176,169,158,151,146,139,148,156],chartTarget=[165,165,165,165,165,165,165,165,165]
export const loads=[['制造板块',84,'高风险 2 家'],['供应链板块',72,'高风险 2 家'],['销售板块',55,'高风险 1 家'],['服务板块',36,'暂无高风险']]
export const issues=[['缺口','上海制造十七日预计出现资金缺口','建议提前启用五千万元授信','待批准'],['回款','华东销售两笔大额回款延期','已由业务负责人重新确认日期','处理中'],['付款','供应链集中付款与税款同日','建议调整非关键供应商付款批次','需协调']].map(x=>({type:x[0],title:x[1],detail:x[2],status:x[3]}))
