/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.cashflowai.service;
import jakarta.validation.constraints.*; import org.springframework.stereotype.Service; import java.math.*; import java.util.*;
@Service public class CashflowForecastService{
 public Result forecast(Request q){BigDecimal closing=q.openingCash().add(q.expectedReceipts30Days()).subtract(q.expectedPayments30Days());BigDecimal available=closing.add(q.committedCredit());BigDecimal gap=available.signum()<0?available.abs():BigDecimal.ZERO;BigDecimal daily=q.expectedPayments30Days().divide(BigDecimal.valueOf(30),2,RoundingMode.HALF_UP);int runway=daily.signum()==0?365:Math.max(0,available.max(BigDecimal.ZERO).divide(daily,0,RoundingMode.DOWN).intValue());int score=0;List<String> drivers=new ArrayList<>();
  if(closing.signum()<0){score+=45;drivers.add("经营现金净流出导致期末余额为负");}if(q.overdueReceivables().compareTo(q.expectedReceipts30Days().multiply(new BigDecimal("0.35")))>0){score+=25;drivers.add("逾期应收占预计回款比例偏高");}if(runway<15){score+=25;drivers.add("可用资金覆盖天数不足十五天");}if(q.forecastConfidencePercent()<70){score+=15;drivers.add("预测数据完整度与可信度不足");}score=Math.min(100,score);String risk=score>=65?"HIGH":score>=35?"MEDIUM":"LOW";if(drivers.isEmpty())drivers.add("未来三十天资金收支保持平衡");String action=risk.equals("HIGH")?"立即启动回款攻坚并准备授信提款":risk.equals("MEDIUM")?"滚动校准付款节奏与回款承诺":"维持周度现金流滚动预测";return new Result(q.entityCode(),closing.setScale(2,RoundingMode.HALF_UP),available.setScale(2,RoundingMode.HALF_UP),gap.setScale(2,RoundingMode.HALF_UP),runway,score,risk,action,drivers);}
 public record Request(@NotBlank String entityCode,@DecimalMin("0") BigDecimal openingCash,@DecimalMin("0") BigDecimal expectedReceipts30Days,@DecimalMin("0") BigDecimal expectedPayments30Days,@DecimalMin("0") BigDecimal overdueReceivables,@DecimalMin("0") BigDecimal committedCredit,@Min(0) @Max(100) int forecastConfidencePercent){}
 public record Result(String entityCode,BigDecimal projectedClosingCash,BigDecimal availableLiquidity,BigDecimal liquidityGap,int runwayDays,int riskScore,String riskLevel,String recommendedAction,List<String> drivers){}
}
