/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.cashflowai;
import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.http.MediaType; import org.springframework.test.web.servlet.MockMvc; import java.util.regex.*; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@SpringBootTest @AutoConfigureMockMvc class CashflowAiApiIntegrationTests{@Autowired MockMvc mvc;String token;/**
                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                               */
@BeforeEach void login()throws Exception{String j=mvc.perform(post("/api/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"username\":\"operator\",\"password\":\"Demo@2026\"}")).andExpect(status().isOk()).andReturn().getResponse().getContentAsString();Matcher m=Pattern.compile("\\\"token\\\":\\\"([^\\\"]+)\\\"").matcher(j);if(!m.find())throw new AssertionError();token=m.group(1);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             */
@Test void forecastsLiquidityRisk()throws Exception{mvc.perform(post("/api/ai/cashflow/forecast").header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content("{\"entityCode\":\"ZH-SH\",\"openingCash\":120000,\"expectedReceipts30Days\":180000,\"expectedPayments30Days\":520000,\"overdueReceivables\":160000,\"committedCredit\":50000,\"forecastConfidencePercent\":62}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.riskLevel").value("HIGH"));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            */
@Test void deniesAnonymous()throws Exception{mvc.perform(post("/api/ai/cashflow/forecast").contentType(MediaType.APPLICATION_JSON).content("{}")).andExpect(status().isUnauthorized());}}
